### PR TITLE
migrate to new Relaton YAML format

### PR DESCRIPTION
**Pull request by andrew2net**
For details see https://github.com/relaton/relaton-calconnect/issues/1#issuecomment-533740877

### CODE REVIEW

**Comment by ronaldtse** [comment]
@andrew2net I'm getting this output, is this correct?

```
echo "Running locally..."; bundle exec relaton concatenate \
	  -t "CalConnect Document Registry" \
		-g "CalConnect" \
	  csd _input/csd.rxl; \
	sed -i "" 's+_input/csd+csd+g' _input/csd.rxl
Running locally...
echo "Running locally..."; bundle exec relaton xml2yamlnew _input/csd.rxl
Running locally...
[relaton] Info: detecting backends:
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_itu" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_ogc" registered
Document type "advisory" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "administrative" is invalid.
Document type "directive" is invalid.
Document type "directive" is invalid.
Document type "directive" is invalid.
Document type "directive" is invalid.
Document type "directive" is invalid.
Document type "report" is invalid.
Document type "report" is invalid.
Document type "advisory" is invalid.
...
```

**Comment by andrew2net** [comment]
> I'm getting this output, is this correct?

@ronaldtse yes, it's correct at this time. We don't have `relaton-calconnect` gem yet. So it uses `relaton-bib` to convert documents, but `relaton-bib` doesn't have these document types in its grammar.

**Comment by ronaldtse** [comment]
@andrew2net is the converter a one-time thing or code we need to maintain?

**Comment by andrew2net** [comment]
@ronaldtse I think we should save it temporally in case `admin.yaml` or `external.yaml` be updated.

**Pull request merged**
