### PR TITLE
Set NODE_PATH after installation script

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/CalConnect/standards.calconnect.org/pull/24

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
build failed because in 43d36a61916c41d1db6d20b56915f763a4ad0a03 `jekyll-paginate-v2` was commented in `Gemfile`

Unfortunately, comment for this commit not very descriptive @ronaldtse maybe you can explain a little bit what you wanna achieve?

**Comment by ronaldtse** [comment]
The “pagination” gem being missing during bundle was one of the errors originally, that’s why I commented it. But apparently I didn’t fully comment it out (it’s not used at all).  Could you help comment it out? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse CI is green now, it's difficult for me to say is everything right, may I ask you to have a look?

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 ! Merging now.

**Pull request merged**
